projection_dim: [768, 384, 192, 96]
projection_dim_x4: 96
# model_id: "runwayml/stable-diffusion-v1-5"
model_id: "/home/kemove/disk/project/stable-diffusion-v1-5"
diffusion_mode: "inversion"
input_resolution: [512, 512] # H, W
#batch_size: 1
prompt: ""
negative_prompt: ""
guidance_scale: -1
# Subsample every 5 steps
#save_timestep: [49, 45, 40, 35, 30, 25, 20, 15, 10, 5, 0]
#num_timesteps: 50

scheduler_timesteps: [80, 60, 40, 20, 1]
save_timestep: [4, 3, 2, 1, 0]
num_timesteps: 5

idxs: [[0, 0], [0, 1], [0, 2], [1, 0], [1, 1], [1, 2], [2, 0], [2, 1], [2, 2], [3, 0], [3, 1], [3, 2]]
